title: PyMaster's Website

author: PyMaster

navbar-links:
  About Me: "Python coder | Problem solver | Always learning 🚀"
  Resources:
  My Home Website: "https://sites.google.com/view/ninjaprosfanclub/home"


avatar: "/main/avatar-icon.png"

round-avatar: true

social-network-links:
  email: "ninjapro.gaming22@gmail.com"
  github: PyMaster
  youtube: "@ninjapro_gaming2022"
  reddit: Turbulent-Cloud-12
  discord: "8v9ebHt7G8"


share-links-active:
  github: true
  youtube: true
  reddit: true
  discord: true
  email: false

title-on-all-pages: true

excerpt_length: 1000



post_search: true

edit_page_button: true


navbar-var-length: true



page-col: "#87CEEB"
text-col: "#000000"
link-col: "#0000FF"
hover-col: "#0000EE"
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"




date_format: "%B %-d, %Y"


timezone: "America/Toronto"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/
